---
parameters:
- name: JOBID
  generate: expression
  from: "[0-9a-f]{7}"
apiVersion: v1
kind: Template
metadata:
  name: deploy-template
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: deploy-job
  spec:
    backoffLimit: 5
    template:
      spec:
        restartPolicy: Never
        containers:
          - image: quay.io/centos/centos:centos8
            imagePullPolicy: Always
            name: assisted-service-post-deploy
            command:
              - curl
            args:
              - ifconfig.co
